services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest # <- update image version here, see: https://github.com/pi-hole/docker-pi-hole/releases
    hostname: pihole.local
    depends_on:
      - unbound
    restart: unless-stopped
    deploy:
      resources: # <- these settings are optional, but can help to limit resource reservations
        limits:
          memory: 768M
        reservations:
          memory: 256M
    ports:
      - "80:80/tcp" # web ui -> http://localhost:8080/admin
      - "53:53/tcp" # DNS tcp port is used as fallback for longer dns messages
      - "53:53/udp" # DNS port
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/pihole/:/etc/pihole/
      - ./conf/dnsmasq.d/:/etc/dnsmasq.d/
    environment:
      PUID: 1000
      PGID: 1000
      WEBPASSWORD: ${WEBPASSWORD}
      FTLCONF_LOCAL_IPV4: ${HOST_IP_V4_ADDRESS} # <-- match ipv4_address of host
      TZ: ${TIMEZONE}
      PIHOLE_DNS_: 172.21.200.3#53 # forward to unbound
      DNSSEC: false
      WEBTHEME: default-darker
    dns:
      - 127.0.0.1
      - 10.23.114.240
    networks:
      pihole_dns_network:
        ipv4_address: 172.21.200.2 # <-- use this ip as dns when connected to pihole_dns_network (i.e. within a docker network)
  unbound:
    #build: ./unbound
    image: klutchell/unbound:latest
    container_name: unbound
    hostname: unbound.local
    restart: unless-stopped
    cap_add: 
      - NET_ADMIN
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE}
    ports:
      - "5335:53/tcp" # expose a different port (5335) so you can use it directly
      - "5335:53/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/unbound:/etc/unbound/
    networks:
      pihole_dns_network:
        ipv4_address: 172.21.200.3 # <-- this is used by pihole as upstream DNS

networks:
  # Define a custom subnet for pihole so that unbound can be an upstream DNS on port 53
  pihole_dns_network:
    name: "pihole_dns_network"
    ipam:
      driver: default
      config:
        - subnet: 172.21.200.0/24
          gateway: 172.21.200.1
          ip_range: 172.21.200.0/24 # 172.21.200.1 - 172.21.200.254
